packages:
  order-commerce:
    actions:
      save-commit-after:
        function: order/commerce/save-commit-after/index.js
        web: 'yes'
        runtime: nodejs:20
        inputs:
          LOG_LEVEL: info
          IIO_EVENTS_WEBHOOK_URL: $IIO_EVENTS_WEBHOOK_URL
